### ISSUE TITLE
not working on macOS 14.1.1

### ISSUE THREAD

**Issue by yurks** [macmade/Sensors#3]
When app started, all sensors are jumping:

https://github.com/macmade/Sensors/assets/4581398/a25de70b-6538-4f04-9ee7-13360cbc18b3

On trying of window resize or scroll, app terminated with [crash report](https://github.com/macmade/Sensors/files/13416496/log.txt)

**Comment by DavidBlowi** [comment]
As of 14.2.1, January 22, 2024: This issue still exists, and I have encountered it on a M3 Max MacBook Pro

**Comment by macmade** [comment]
Fixed in 1.2.1: https://github.com/macmade/Sensors/releases/tag/1.2.1
